name: Build with Clean

on:
  push:
    branches-ignore:
      - v1
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: AutoModality/action-clean@v1
      - uses: actions/checkout@v2
      - run: echo Hello World
